FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get install -y sendmail \
    && apt-get install -y cron

COPY script.sh /script.sh
RUN chmod +x /script.sh

COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab \
    && touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log
